[dev]
tauri = { cmd = [{ cmd = "cargo tauri dev", working_dir = "crates/backend" }] }
[build]
tauri = { cmd = [

    { cmd = "cargo tauri build", working_dir = "crates/backend" },
] }
[setup]
all = { cmd = [
    { cmd = "npm i -g pnpm --silent", working_dir = "crates/frontend" },
    { cmd = "pnpm i", working_dir = "crates/frontend" },
] }